/* AIHXO · Cobros individuales e historial */
(function(){
 const N=v=>Number(v||0),E=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
 const pending=o=>Math.max(0,N(o.total)-N(o.amount_paid));
 let list=[],payments=[],requests=new Map(),saving=new Set();
 window.cajaCobrosView=async function(c){
  const [a,b]=await Promise.all([supabaseClient.from('orders').select('*').order('created_at',{ascending:false}),supabaseClient.from('order_payments').select('*').order('paid_at',{ascending:false})]);
  if(a.error||b.error){c.innerHTML='<div class="page"><div class="card">No se pudieron cargar los cobros. <button id="cashRetry" class="secondary">Reintentar</button></div></div>';c.querySelector('#cashRetry').onclick=()=>cajaCobrosView(c);return}
  list=a.data||[];payments=b.data||[];
  const active=list.filter(o=>String(o.status).toLowerCase()!=='cancelado'),methods={};
  for(const o of active){const history=payments.filter(p=>p.order_id===o.id);if(history.length)history.forEach(p=>methods[p.method]=(methods[p.method]||0)+N(p.amount));else if(N(o.amount_paid))methods[o.payment_method||'Sin método']=(methods[o.payment_method||'Sin método']||0)+N(o.amount_paid)}
  c.innerHTML=`<div class="page"><h2>💳 Caja y cobros</h2><div class="grid kpis">${kpi('Ventas',money(active.reduce((a,o)=>a+N(o.total),0)))}${kpi('Cobrado',money(active.reduce((a,o)=>a+N(o.amount_paid),0)))}${kpi('Pendiente',money(active.reduce((a,o)=>a+pending(o),0)))}</div><div class="card"><h3>Cobros por método · pedidos no cancelados</h3>${Object.entries(methods).map(([m,v])=>`<div class="statline"><span>${E(m)}</span><b>${money(v)}</b></div>`).join('')||'Sin cobros'}</div><div class="card"><input id="cashSearch" type="search" placeholder="Buscar cliente o número de pedido"><select id="cashFilter"><option value="pending">Pendientes</option><option value="all">Todos, incluidos cancelados</option><option value="paid">Pagados</option></select></div><div id="cashList"></div></div>`;
  if(window._aihxoCashFocus){$('#cashFilter').value='all';$('#cashSearch').value=list.find(o=>o.id===window._aihxoCashFocus)?.order_number||'';window._aihxoCashFocus=null}
  $('#cashFilter').onchange=window.dibujarCajaCobros;$('#cashSearch').oninput=window.dibujarCajaCobros;dibujarCajaCobros();
 };
 window.dibujarCajaCobros=function(){const mode=$('#cashFilter').value,q=$('#cashSearch').value.toLowerCase();$('#cashList').innerHTML=list.filter(o=>`${o.order_number} ${o.customer_name}`.toLowerCase().includes(q)&&(mode==='all'||(mode==='pending'?pending(o)>.009&&String(o.status).toLowerCase()!=='cancelado':pending(o)<=.009))).map(o=>{
  const ps=payments.filter(p=>p.order_id===o.id);return `<div class="card" style="margin-top:12px"><h3>${E(o.order_number)} · ${E(o.customer_name)}</h3><div>${E(o.status)} · Total ${money(o.total)} · Cobrado ${money(o.amount_paid)} · <b>Pendiente ${money(pending(o))}</b></div>
  <details style="margin:12px 0"><summary>Historial de cobros (${ps.length})</summary>${ps.map(p=>`<div class="statline"><span>${E(new Date(p.paid_at).toLocaleString('es-ES'))} · ${E(p.method)}<br><small>${E(p.note)}</small></span><b>${money(p.amount)}</b></div>`).join('')||(N(o.amount_paid)?`<div>Saldo anterior: ${money(o.amount_paid)} · ${E(o.payment_method||'Sin método')}. No consta desglose.</div>`:'Sin cobros registrados')}</details>
  <form class="cashForm" data-id="${o.id}"><div class="formgrid"><div class="field"><label>Movimiento</label><select name="kind"><option value="payment">Cobro</option><option value="refund">Devolución</option></select></div><div class="field"><label>Importe de este movimiento €</label><input name="amount" type="number" min=".01" step=".01" required></div><div class="field"><label>Método</label><select name="method" required><option value="">Selecciona</option>${['Efectivo','Transferencia','PayPal','Tarjeta','Bizum','Otro'].map(m=>`<option>${m}</option>`).join('')}</select></div><div class="field"><label>Fecha</label><input name="date" type="date" value="${new Date().toLocaleDateString('en-CA')}" required></div></div><div class="field"><label>Nota / motivo de devolución</label><input name="note"></div><button class="primary">Registrar movimiento</button><div class="cashStatus" role="status"></div></form><button class="secondary cashDetail" data-id="${o.id}" style="margin-top:8px">Ficha del pedido</button></div>`}).join('')||'<div class="card">Sin pedidos para este filtro.</div>';
  document.querySelectorAll('.cashDetail').forEach(b=>b.onclick=()=>abrirFichaPedido(b.dataset.id));
  document.querySelectorAll('.cashForm').forEach(f=>f.onsubmit=async e=>{e.preventDefault();const id=f.dataset.id;if(saving.has(id))return;saving.add(id);const btn=f.querySelector('button');btn.disabled=true;const fd=new FormData(f),request=requests.get(id)||crypto.randomUUID();requests.set(id,request);
   try{const {data,error}=await supabaseClient.rpc('record_order_payment',{p_id:request,p_order_id:id,p_amount:N(fd.get('amount'))*(fd.get('kind')==='refund'?-1:1),p_method:fd.get('method'),p_note:fd.get('note'),p_paid_at:new Date(String(fd.get('date'))+'T12:00:00').toISOString()});if(error)throw error;requests.delete(id);const o=orders.find(o=>o.id===id);if(o)Object.assign(o,data);toast('Movimiento registrado');window._aihxoCashFocus=id;await cajaCobrosView($('#view'))}catch(err){f.querySelector('.cashStatus').textContent=err.message}finally{saving.delete(id);btn.disabled=false}
  });
 };
 const old=window.setView;window.setView=function(v){if(v==='cash'){document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===v));$('#title').textContent='Caja y cobros';cajaCobrosView($('#view'));closeMobileMenu();return}return old(v)};
 function nav(){const b=document.querySelector('#nav button[data-view="expenses"]');if(!b||document.querySelector('#nav button[data-view="cash"]'))return;const n=document.createElement('button');n.dataset.view='cash';n.innerHTML='💳 <span>Caja y cobros</span>';n.onclick=()=>setView('cash');b.insertAdjacentElement('afterend',n)}setTimeout(nav,0);
})();
