/* AIHXO · Caja y cobros */
(function(){
 const N=v=>Number(v||0), norm=v=>String(v||'').trim().toLowerCase();
 const valid=o=>norm(o.status)!=='cancelado';
 const pending=o=>Math.max(0,N(o.total)-N(o.amount_paid));
 window.cajaCobrosView=async function(c){
   const {data,error}=await supabaseClient.from('orders').select('*').order('created_at',{ascending:false});
   if(error){console.error(error);c.innerHTML='<div class="page"><div class="card">No se pudieron cargar los cobros.</div></div>';return}
   const list=(data||[]).filter(valid);window._aihxoCajaOrders=list;
   const sales=list.reduce((a,o)=>a+N(o.total),0), paid=list.reduce((a,o)=>a+Math.min(N(o.total),N(o.amount_paid)),0), due=list.reduce((a,o)=>a+pending(o),0);
   const partial=list.filter(o=>norm(o.payment_status)==='parcial').length, unpaid=list.filter(o=>pending(o)>0.009).length;
   const methods={};list.forEach(o=>{if(N(o.amount_paid)>0){const m=o.payment_method||'Sin método';methods[m]=(methods[m]||0)+N(o.amount_paid)}});
   c.innerHTML=`<div class="page"><div class="section"><div><h2>💳 Caja y cobros</h2><div class="muted">Qué hemos vendido, qué hemos cobrado y qué queda pendiente</div></div></div>
   <div class="grid kpis">${kpi('Ventas',money(sales),list.length+' pedidos')}${kpi('Cobrado',money(paid),'registrado')}${kpi('Pendiente',money(due),unpaid+' pedidos')}${kpi('Pagos parciales',partial,'a revisar')}</div>
   <div class="grid two"><div class="card"><h3>💰 Cobros por método</h3>${Object.keys(methods).length?Object.entries(methods).sort((a,b)=>b[1]-a[1]).map(([m,v])=>`<div class="statline"><span>${esc(m)}</span><b>${money(v)}</b></div>`).join(''):'<div class="empty">Todavía no hay cobros registrados.</div>'}</div><div class="card"><h3>⚠️ Pendientes de cobro</h3><div class="muted">Pedidos no cancelados con importe pendiente.</div><div style="margin-top:10px">${unpaid?`<b style="font-size:28px">${unpaid}</b> pedidos pendientes`:'✅ Todo cobrado'}</div></div></div>
   <div class="card" style="margin-top:14px"><div class="section"><h3>Pedidos y cobros</h3><select id="cashFilter" onchange="dibujarCajaCobros()" style="width:auto"><option value="pending">Pendientes</option><option value="all">Todos</option><option value="paid">Pagados</option></select></div><div id="cashList"></div></div></div>`;
   dibujarCajaCobros();
 };
 window.dibujarCajaCobros=function(){const mode=$('#cashFilter')?.value||'pending';let list=window._aihxoCajaOrders||[];if(mode==='pending')list=list.filter(o=>pending(o)>0.009);if(mode==='paid')list=list.filter(o=>pending(o)<=0.009);$('#cashList').innerHTML=list.length?list.map(o=>{const due=pending(o);return `<div class="card" style="margin-top:10px"><div class="section"><div><b>${esc(o.order_number||'Pedido')}</b><div class="muted">${esc(o.customer_name||'')} · ${esc(o.order_date||'')}</div></div><div style="text-align:right"><b>${money(o.total)}</b><div class="muted">Pendiente ${money(due)}</div></div></div><div class="grid two"><div class="field"><label>Estado</label><select id="cashStatus-${o.id}">${['Pendiente','Parcial','Pagado'].map(x=>`<option ${String(o.payment_status||'Pendiente')===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Método</label><select id="cashMethod-${o.id}"><option value="">—</option>${['Efectivo','Transferencia','PayPal','Tarjeta','Bizum','Otro'].map(x=>`<option ${String(o.payment_method||'')===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Importe cobrado</label><input id="cashPaid-${o.id}" type="number" min="0" step="0.01" value="${N(o.amount_paid)}"></div><div style="display:flex;align-items:end"><button class="primary" style="width:100%" onclick="guardarCobro('${o.id}')">Guardar cobro</button></div></div><button class="secondary" style="width:100%;margin-top:8px" onclick="abrirFichaPedido('${o.id}')">📋 Abrir ficha completa</button></div>`}).join(''):'<div class="empty">No hay pedidos en esta vista.</div>'};
 window.guardarCobro=async function(id){const o=(window._aihxoCajaOrders||[]).find(x=>x.id===id);if(!o)return;let amount=N($(`#cashPaid-${id}`).value),status=$(`#cashStatus-${id}`).value,method=$(`#cashMethod-${id}`).value||null;amount=Math.max(0,Math.min(N(o.total),amount));if(status==='Pagado')amount=N(o.total);else if(amount>=N(o.total)&&N(o.total)>0)status='Pagado';else if(amount>0)status='Parcial';else status='Pendiente';const patch={payment_status:status,payment_method:method,amount_paid:amount,paid_at:status==='Pagado'?(o.paid_at||new Date().toISOString()):null};const {error}=await supabaseClient.from('orders').update(patch).eq('id',id);if(error){console.error(error);toast('No se pudo guardar el cobro');return}Object.assign(o,patch);const globalOrder=orders.find(x=>x.id===id);if(globalOrder)Object.assign(globalOrder,patch);toast('Cobro actualizado');cajaCobrosView($('#view'))};
 const old=window.setView;window.setView=function(v){if(v==='cash'){document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===v));$('#title').textContent='Caja y cobros';cajaCobrosView($('#view'));closeMobileMenu();return}return old(v)};
 function nav(){const expensesBtn=document.querySelector('#nav button[data-view="expenses"]');if(!expensesBtn||document.querySelector('#nav button[data-view="cash"]'))return;const b=document.createElement('button');b.dataset.view='cash';b.innerHTML='💳 <span>Caja y cobros</span>';b.onclick=()=>setView('cash');expensesBtn.insertAdjacentElement('afterend',b)}setTimeout(nav,0);
})();