/* AIHXO Creative Studio v1 — editor local de conceptos y mockups, sin generación IA remota */
(function(){
 if(window.__aihxoCreativeStudio)return;window.__aihxoCreativeStudio=true;
 const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;':'&quot;',"'":'&#39;'}[c]));
 const scenes={studio:['#ebeff4','#ced7e0'],urbano:['#0a1024','#2a3c60'],playa:['#b8e4f1','#e4c9a4'],minimal:['#f6f6f2','#d9dad4']};
 let state={idea:'',scene:'studio',shirt:'#111827',placement:'front',size:44,x:50,y:43,design:null,designName:'',widthCm:25,heightCm:30};
 const $=id=>document.getElementById(id);
 function mountNav(){const nav=document.querySelector('#nav');if(!nav||nav.querySelector('#aihxoCreativeNav'))return;const b=document.createElement('button');b.id='aihxoCreativeNav';b.type='button';b.innerHTML='✨ <span>Creative Studio</span>';b.onclick=()=>{window.renderAIHXOCreativeStudio();if(typeof closeMobileMenu==='function')closeMobileMenu()};const reels=nav.querySelector('[data-aihxo-reels-static]');if(reels)reels.before(b);else nav.append(b);}
 function shirtPath(ctx){ctx.beginPath();ctx.moveTo(200,205);ctx.lineTo(153,224);ctx.lineTo(112,332);ctx.lineTo(170,358);ctx.lineTo(195,312);ctx.lineTo(195,610);ctx.lineTo(465,610);ctx.lineTo(465,312);ctx.lineTo(490,358);ctx.lineTo(548,332);ctx.lineTo(507,224);ctx.lineTo(460,205);ctx.lineTo(406,187);ctx.quadraticCurveTo(330,250,254,187);ctx.closePath();}
 function draw(){const c=$('crCanvas');if(!c)return;const ctx=c.getContext('2d');const w=c.width,h=c.height;const [a,b]=scenes[state.scene];const g=ctx.createLinearGradient(0,0,w,h);g.addColorStop(0,a);g.addColorStop(1,b);ctx.fillStyle=g;ctx.fillRect(0,0,w,h);if(state.scene==='urbano'){ctx.fillStyle='#ffffff18';for(let i=0;i<10;i++)ctx.fillRect(i*76,180+(i%3)*50,42,330)}if(state.scene==='playa'){ctx.fillStyle='#f6e4ba';ctx.fillRect(0,645,w,235);ctx.fillStyle='#80bfd8';ctx.fillRect(0,560,w,86)}
 ctx.save();ctx.shadowColor='#0005';ctx.shadowBlur=26;ctx.shadowOffsetY=17;shirtPath(ctx);ctx.fillStyle=state.shirt;ctx.fill();ctx.restore();shirtPath(ctx);ctx.strokeStyle='#ffffff29';ctx.lineWidth=3;ctx.stroke();
 ctx.beginPath();ctx.ellipse(330,203,68,31,0,0,Math.PI*2);ctx.strokeStyle='#ffffff55';ctx.lineWidth=5;ctx.stroke();
 if(state.design){const img=state.design, maxW=(state.size/100)*270,maxH=(state.size/100)*330;const factor=Math.min(maxW/img.width,maxH/img.height);const dw=img.width*factor,dh=img.height*factor;const px=195+state.x/100*270,py=270+state.y/100*280;ctx.drawImage(img,px-dw/2,py-dh/2,dw,dh);}
 ctx.fillStyle=state.scene==='urbano'?'#ffffff':'#152338';ctx.font='700 24px system-ui';ctx.fillText('AIHXO',26,54);ctx.font='15px system-ui';ctx.fillText('PREVISUALIZACIÓN · NO APTO PARA IMPRESIÓN',26,80);
 }
 function render(){mountNav();const v=$('view');if(!v)return;document.querySelectorAll('#nav button').forEach(b=>b.classList.remove('active'));$('aihxoCreativeNav')?.classList.add('active');if($('title'))$('title').textContent='Creative Studio';
 v.innerHTML=`<div class="card" style="max-width:1150px;margin:auto;padding:18px"><h2 style="margin:0 0 6px">✨ AIHXO Creative Studio</h2><p class="muted">Briefing, mockup editable y presentación para redes. La generación automática con IA todavía no está conectada.</p><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:18px"><section><label>Idea o concepto<textarea id="crIdea" rows="4" placeholder="Describe el diseño que quieres crear...">${esc(state.idea)}</textarea></label><label>Subir diseño PNG (preferiblemente transparente)<input type="file" id="crUpload" accept="image/png,image/jpeg,image/webp"></label><label>Escenario<select id="crScene"><option value="studio">Estudio</option><option value="urbano">Urbano nocturno</option><option value="playa">Playa ilustrativa</option><option value="minimal">Minimalista</option></select></label><label>Color de camiseta <input type="color" id="crShirt" value="${esc(state.shirt)}"></label><label>Tamaño visual <input type="range" id="crSize" min="12" max="85" value="${state.size}"></label><label>Horizontal <input type="range" id="crX" min="0" max="100" value="${state.x}"></label><label>Vertical <input type="range" id="crY" min="0" max="100" value="${state.y}"></label><div style="display:grid;grid-template-columns:1fr 1fr;gap:8px"><label>Ancho DTF (cm)<input id="crW" type="number" min="1" max="40" value="${state.widthCm}"></label><label>Alto DTF (cm)<input id="crH" type="number" min="1" max="50" value="${state.heightCm}"></label></div><p class="muted" style="font-size:12px">Las medidas DTF son una referencia del briefing: este mockup no reescala ni certifica el fichero de impresión.</p><button id="crSave" type="button" class="secondary">Guardar concepto</button> <button id="crLoad" type="button" class="secondary">Recuperar concepto</button><button id="crExport" type="button" class="primary" style="margin-top:10px;width:100%">Descargar imagen promocional PNG</button><p id="crStatus" class="muted" role="status"></p></section><section><canvas id="crCanvas" width="660" height="880" style="width:100%;height:auto;max-width:580px;border-radius:14px;border:1px solid #ccd4df;touch-action:none"></canvas><p class="muted">Puedes arrastrar el diseño sobre la camiseta. El escenario es ilustrativo, no una fotografía generada por IA.</p></section></div></div>`;
 $('crScene').value=state.scene;const sync=()=>{state.idea=$('crIdea').value;state.scene=$('crScene').value;state.shirt=$('crShirt').value;state.size=+$('crSize').value;state.x=+$('crX').value;state.y=+$('crY').value;state.widthCm=+$('crW').value;state.heightCm=+$('crH').value;draw();};
 ['crIdea','crScene','crShirt','crSize','crX','crY','crW','crH'].forEach(id=>$(id).addEventListener('input',sync));
 $('crUpload').onchange=async e=>{const f=e.target.files?.[0];if(!f)return;if(!/^image\/(png|jpeg|webp)$/.test(f.type)||f.size>12*1024*1024){$('crStatus').textContent='Usa PNG, JPG o WebP de menos de 12 MB';return;}const url=URL.createObjectURL(f);try{const im=new Image();await new Promise((ok,bad)=>{im.onload=ok;im.onerror=bad;im.src=url});state.design=im;state.designName=f.name;draw();$('crStatus').textContent='Diseño cargado: '+f.name;}catch(e){$('crStatus').textContent='No se pudo leer la imagen';}finally{URL.revokeObjectURL(url);}};
 let dragging=false;const c=$('crCanvas');const pointer=e=>{const rect=c.getBoundingClientRect(),x=(e.clientX-rect.left)/rect.width*660,y=(e.clientY-rect.top)/rect.height*880;state.x=Math.max(0,Math.min(100,(x-195)/270*100));state.y=Math.max(0,Math.min(100,(y-270)/280*100));$('crX').value=state.x;$('crY').value=state.y;draw();};c.addEventListener('pointerdown',e=>{if(!state.design)return;dragging=true;c.setPointerCapture(e.pointerId);pointer(e)});c.addEventListener('pointermove',e=>{if(dragging)pointer(e)});c.addEventListener('pointerup',()=>dragging=false);c.addEventListener('pointercancel',()=>dragging=false);
 $('crSave').onclick=()=>{sync();try{localStorage.setItem('aihxoCreativeConceptV1',JSON.stringify({...state,design:null}));$('crStatus').textContent='Briefing guardado en este dispositivo. Imagen no guardada: vuelve a subirla al recuperar.';}catch(e){$('crStatus').textContent='No se pudo guardar el concepto';}};
 $('crLoad').onclick=()=>{try{const s=JSON.parse(localStorage.getItem('aihxoCreativeConceptV1')||'null');if(!s)throw Error('No hay concepto guardado');state={...state,...s,design:null};render();}catch(e){$('crStatus').textContent=e.message;}};
 $('crExport').onclick=()=>{draw();c.toBlob(blob=>{if(!blob){$('crStatus').textContent='No se pudo exportar';return;}const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='AIHXO-creative-mockup.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),4000);},'image/png');};draw();}
 window.renderAIHXOCreativeStudio=render;
 const observer=new MutationObserver(()=>{if(document.querySelector('#nav')&&!document.getElementById('aihxoCreativeNav'))mountNav();});observer.observe(document.documentElement,{childList:true,subtree:true});mountNav();
})();