/* AIHXO · Generador de mockups rápidos para diseños propios */
(function(){
 const $m=s=>document.querySelector(s);
 let designImg=null;
 function panel(){let p=$m('#aihxoMockupPanel');if(p)return p;p=document.createElement('div');p.id='aihxoMockupPanel';p.style.cssText='position:fixed;inset:0;z-index:10000;background:rgba(7,21,47,.55);display:flex;align-items:flex-end;justify-content:center';p.innerHTML=`<div style="background:#fff;width:min(760px,100%);max-height:94vh;overflow:auto;border-radius:24px 24px 0 0;padding:18px;box-sizing:border-box"><div style="display:flex;justify-content:space-between;align-items:center"><div><h2 style="margin:0;color:#07152f">👕 Crear mockup</h2><div style="color:#667085;margin-top:4px">Previsualiza el diseño sobre una camiseta y guarda el PNG.</div></div><button id="mkClose" type="button" style="border:0;background:#eef3f9;border-radius:12px;padding:10px 13px;font-weight:900">✕</button></div><div style="display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:16px"><label>Vista<select id="mkSide" class="dp-input"><option value="front">Delantera</option><option value="back">Trasera</option></select></label><label>Color<input id="mkColor" type="color" value="#ffffff" class="dp-input" style="height:48px;padding:5px"></label></div><label style="display:block;margin-top:12px;font-weight:800">Diseño PNG/JPG<input id="mkFile" type="file" accept="image/*" class="dp-input"></label><div style="font-size:12px;color:#667085;margin-top:6px">Si acabas de seleccionar la foto principal del diseño, intentaremos usarla automáticamente.</div><canvas id="mkCanvas" width="1000" height="1100" style="width:100%;margin-top:14px;border-radius:18px;background:#f2f4f7"></canvas><div style="display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:12px"><label>Tamaño diseño<input id="mkScale" type="range" min="15" max="70" value="42" style="width:100%"></label><label>Altura<input id="mkY" type="range" min="18" max="65" value="34" style="width:100%"></label></div><button id="mkDownload" type="button" class="primary" style="width:100%;margin-top:14px;padding:15px">Guardar mockup PNG</button></div>`;document.body.appendChild(p);$m('#mkClose').onclick=()=>p.remove();$m('#mkFile').onchange=e=>loadFile(e.target.files?.[0]);['#mkSide','#mkColor','#mkScale','#mkY'].forEach(s=>$m(s).oninput=draw);$m('#mkDownload').onclick=download;return p}
 function shirt(ctx,color,side){ctx.clearRect(0,0,1000,1100);ctx.fillStyle='#f2f4f7';ctx.fillRect(0,0,1000,1100);ctx.save();ctx.shadowColor='rgba(0,0,0,.16)';ctx.shadowBlur=28;ctx.shadowOffsetY=14;ctx.fillStyle=color;ctx.beginPath();ctx.moveTo(330,170);ctx.lineTo(215,215);ctx.lineTo(90,385);ctx.lineTo(210,465);ctx.lineTo(280,380);ctx.lineTo(280,940);ctx.quadraticCurveTo(500,990,720,940);ctx.lineTo(720,380);ctx.lineTo(790,465);ctx.lineTo(910,385);ctx.lineTo(785,215);ctx.lineTo(670,170);ctx.quadraticCurveTo(500,255,330,170);ctx.closePath();ctx.fill();ctx.restore();ctx.strokeStyle='rgba(0,0,0,.16)';ctx.lineWidth=4;ctx.stroke();if(side==='front'){ctx.fillStyle='#f2f4f7';ctx.beginPath();ctx.ellipse(500,178,93,53,0,0,Math.PI*2);ctx.fill();ctx.strokeStyle='rgba(0,0,0,.12)';ctx.stroke()}else{ctx.strokeStyle='rgba(0,0,0,.10)';ctx.beginPath();ctx.arc(500,178,94,0.18,Math.PI-.18);ctx.stroke()}}
 function draw(){const c=$m('#mkCanvas');if(!c)return;const ctx=c.getContext('2d'),side=$m('#mkSide').value;color=$m('#mkColor').value;shirt(ctx,color,side);if(!designImg){ctx.fillStyle='#667085';ctx.font='700 28px sans-serif';ctx.textAlign='center';ctx.fillText('Selecciona el archivo del diseño',500,560);return}const maxW=Number($m('#mkScale').value)/100*440,maxH=420,ratio=Math.min(maxW/designImg.width,maxH/designImg.height),w=designImg.width*ratio,h=designImg.height*ratio,y=Number($m('#mkY').value)/100*900;ctx.drawImage(designImg,500-w/2,y-h/2,w,h)}
 function loadFile(file){if(!file)return;const r=new FileReader();r.onload=()=>{const im=new Image();im.onload=()=>{designImg=im;draw()};im.src=r.result};r.readAsDataURL(file)}
 function download(){const c=$m('#mkCanvas');if(!c)return;const a=document.createElement('a');const name=($m('#dpNombre')?.value||'AIHXO').trim().replace(/[^a-z0-9]+/gi,'-');a.download=`${name}-mockup-${$m('#mkSide').value}.png`;a.href=c.toDataURL('image/png',1);a.click()}
 window.abrirGeneradorMockup=function(){panel();draw();const f=$m('#dpFoto')?.files?.[0];if(f)loadFile(f)};
 function install(){const form=$m('#formDisenoPropio');if(!form||$m('#dpMockupBtn'))return;const photo=$m('#dpFoto');if(!photo)return;const b=document.createElement('button');b.id='dpMockupBtn';b.type='button';b.textContent='👕 CREAR MOCKUP';b.style.cssText='width:100%;border:1px solid #087cf4;border-radius:16px;background:#eef6ff;color:#087cf4;padding:15px 18px;font-size:15px;font-weight:900;cursor:pointer;margin:-4px 0 18px';b.onclick=()=>window.abrirGeneradorMockup();photo.closest('label')?.insertAdjacentElement('afterend',b)}
 new MutationObserver(install).observe(document.documentElement,{childList:true,subtree:true});setTimeout(install,500);
})();