/* AIHXO · Rentabilidad + Compras */
(function(){
 const N=v=>Number(v||0), ok=o=>String(o.status||'').toLowerCase()!=='cancelado';
 const actualCost=o=>N(o.garment_actual_cost)+N(o.dtf_actual_cost)+N(o.packaging_cost)+N(o.supplier_shipping_cost)+N(o.extras_actual_cost);
 window.rentabilidadView=async function(c){
  const [{data:ex},{data:stock}]=await Promise.all([supabaseClient.from('expenses').select('*'),supabaseClient.from('base_stock_items').select('quantity,unit_cost')]);
  const valid=orders.filter(ok), sales=valid.reduce((a,o)=>a+N(o.total),0), real=valid.reduce((a,o)=>a+actualCost(o),0), legacy=valid.reduce((a,o)=>a+N(o.product_cost),0);
  const known=valid.filter(o=>actualCost(o)>0).length, costs=real||legacy, gross=sales-costs, expensesTotal=(ex||[]).reduce((a,x)=>a+N(x.amount),0), net=gross-expensesTotal, stockValue=(stock||[]).reduce((a,x)=>a+N(x.quantity)*N(x.unit_cost),0);
  const ranked=valid.map(o=>{const cost=actualCost(o)||N(o.product_cost);return {...o,_cost:cost,_margin:N(o.total)-cost}}).sort((a,b)=>b._margin-a._margin);
  c.innerHTML=`<div class="page"><div class="section"><div><h2>📈 Rentabilidad real</h2><div class="muted">Ventas, costes, gastos y margen de AIHXO</div></div></div><div class="grid kpis">${kpi('Ventas',money(sales),valid.length+' pedidos no cancelados')}${kpi('Coste producción',money(costs),known+'/'+valid.length+' con coste real')}${kpi('Margen bruto',money(gross),sales?((gross/sales)*100).toFixed(1)+'%':'')}${kpi('Gastos',money(expensesTotal),'gastos generales')}${kpi('Resultado',money(net),'después de gastos')}${kpi('Dinero en stock',money(stockValue),'coste del inventario')}</div><div class="card"><div class="section"><div><h2>🏆 Rentabilidad por pedido</h2><div class="muted">Ordenados por margen</div></div></div><div class="table-wrap"><table><thead><tr><th>Pedido</th><th>Cliente</th><th>Venta</th><th>Coste</th><th>Margen</th></tr></thead><tbody>${ranked.map(o=>`<tr><td><b>${esc(o.order_number||'')}</b></td><td>${esc(o.customer_name||'')}</td><td>${money(o.total)}</td><td>${money(o._cost)}</td><td><b>${money(o._margin)}</b></td></tr>`).join('')}</tbody></table></div></div>${known<valid.length?`<div class="card" style="margin-top:14px">⚠️ <b>${valid.length-known} pedidos todavía no tienen desglose de coste real.</b><div class="muted">Puedes completarlo desde Pedidos → Ficha completa. Mientras tanto se utiliza el coste histórico cuando existe.</div></div>`:''}</div>`;
 };
 window.comprasView=async function(c){
  const [{data:suppliers},{data:purchases,error}]=await Promise.all([supabaseClient.from('suppliers').select('*').order('name'),supabaseClient.from('purchases').select('*,suppliers(name)').order('purchase_date',{ascending:false})]);if(error){console.error(error);return}
  const ps=purchases||[], total=ps.reduce((a,p)=>a+N(p.amount),0), pending=ps.filter(p=>!['recibido','completado','pagado'].includes(String(p.status||'').toLowerCase()));
  c.innerHTML=`<div class="page"><div class="section"><div><h2>🛒 Compras y proveedores</h2><div class="muted">Pedidos de material y gasto con proveedores</div></div><div style="display:flex;gap:8px;flex-wrap:wrap"><button id="recvCamera" type="button" class="secondary">📷 Recibir con cámara</button><button class="primary" onclick="nuevaCompra()">＋ Nueva compra</button></div></div><div class="grid kpis">${kpi('Compras',ps.length,'registradas')}${kpi('Importe',money(total),'total histórico')}${kpi('Pendientes',pending.length,'por recibir/cerrar')}${kpi('Proveedores',(suppliers||[]).length,'registrados')}</div><div class="card"><div class="table-wrap"><table><thead><tr><th>Fecha</th><th>Proveedor</th><th>Compra</th><th>Importe</th><th>Estado</th><th></th></tr></thead><tbody>${ps.map(p=>`<tr><td>${esc(p.purchase_date||'')}</td><td>${esc(p.suppliers?.name||'—')}</td><td><b>${esc(p.purchase_number||p.description||'Compra')}</b><br><span class="muted">${esc(p.description||'')}</span></td><td>${money(p.amount)}</td><td>${esc(p.status||'')}</td><td><button type="button" class="secondary recvPurchase" data-purchase-id="${p.id}">📷 Recibir</button></td></tr>`).join('')}</tbody></table></div></div></div>`;
  window._aihxoSuppliers=suppliers||[];
  const abrir=pid=>{
   if(typeof window.abrirRecepcionEtiquetas==='function') window.abrirRecepcionEtiquetas(pid||null);
   else { console.error('recepcion-etiquetas.js no está disponible'); toast('No se pudo abrir la cámara. Recarga Gestión e inténtalo de nuevo.'); }
  };
  c.querySelector('#recvCamera')?.addEventListener('click',()=>abrir(null));
  c.querySelectorAll('.recvPurchase').forEach(btn=>btn.addEventListener('click',()=>abrir(btn.dataset.purchaseId)));
 };
 window.nuevaCompra=function(){const ss=window._aihxoSuppliers||[];$('#drawerBody').innerHTML=`<h2>🛒 Nueva compra</h2><form id="buyForm" class="form"><div class="field"><label>Proveedor</label><select name="supplier_id" required><option value="">Selecciona</option>${ss.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('')}</select></div><div class="field"><label>Número / referencia</label><input name="purchase_number"></div><div class="field"><label>Descripción</label><input name="description" required></div><div class="field"><label>Importe €</label><input name="amount" type="number" min="0" step="0.01" required></div><div class="field"><label>Fecha</label><input name="purchase_date" type="date" value="${new Date().toISOString().slice(0,10)}" required></div><div class="field"><label>Estado</label><select name="status"><option>Pedido</option><option>Pagado</option><option>Recibido</option></select></div><div class="field"><label>Notas</label><textarea name="notes"></textarea></div><button class="primary">Guardar compra</button></form>`;openDrawer();$('#buyForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),payload=Object.fromEntries(f.entries());payload.amount=N(payload.amount);const {error}=await supabaseClient.from('purchases').insert(payload);if(error){console.error(error);toast('No se pudo guardar');return}toast('Compra registrada');closeDrawer();comprasView($('#view'))}}
 const old=window.setView;window.setView=function(v){if(v==='profitability'||v==='purchases'){document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===v));$('#title').textContent=v==='profitability'?'Rentabilidad':'Compras';(v==='profitability'?rentabilidadView:comprasView)($('#view'));closeMobileMenu();return}return old(v)};
 function nav(){const reports=document.querySelector('#nav button[data-view="reports"]');if(!reports||document.querySelector('#nav button[data-view="profitability"]'))return;const a=document.createElement('button');a.dataset.view='profitability';a.innerHTML='📈 <span>Rentabilidad</span>';a.onclick=()=>setView('profitability');reports.insertAdjacentElement('beforebegin',a);const b=document.createElement('button');b.dataset.view='purchases';b.innerHTML='🛒 <span>Compras</span>';b.onclick=()=>setView('purchases');reports.insertAdjacentElement('beforebegin',b)}setTimeout(nav,0);
})();